services:
  - type: web
    name: mini-e-commerce-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: your_mongodb_connection_string_here
      - key: PORT
        value: "5000"
